[pytest]
testpaths = automation/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --html=reports/api_test_report.html --self-contained-html
markers =
    auth: Authentication test cases
    projects: Project module test cases
    tasks: Task module test cases
    users: Admin User test cases
    dashboard: Dashboard metric test cases
    db_validation: Database direct verification tests
    negative: Negative path test cases
